version: "3"
services:
  redis:
    restart: always
    image: redis:alpine
    container_name: redis-webchat
    ports:
      - 6379:6379

  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql-webchat
    command: --character-set-server=utf8mb4
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=webchat"
      - "TZ=Asia/Shanghai"
    ports:
      - 33060:3306
